name: run discord bot with token
on:
  push:
    branches: [ main ]

jobs:
  call-api:
    runs-on: ubuntu-latest
    environment: prod

  steps:
    - name: Run bot
      env:
        DISCORD_BOT: ${{ secrets.DISCORD_BOT }}
      run: python bot.py
